

[menus]

  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    identifier = 'Repair Guides'
    name = 'Repair Guides'
    pageRef = '/RepairGuides'
    weight = 20
  [[menus.main]]
    identifier = 'Get Certified'
    name = 'Get Certified'
    pageRef = '/GetCertifed'
    weight = 30
