baseURL = "https://symphonious-zuccutto-ade378.netlify.app/"
languageCode = "en-us"
title = "Right 2 Repair"
featured_image= "/images/right2repair.png"
theme ="ananke"
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  software = "softwares"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Get Certified'
    pageRef = '/GetCertified'
    weight = 20
  [[menus.main]]
    name = 'Forums'
    pageRef = '/Forums'
    weight = 30
  [[menus.main]]
    name = 'Guides'
    pageRef = '/Guides'
    weight = 40
  
  [[menus.main]]
    name = 'Contact' 
    url = "/About/Contact"
    weight = 50 
    parent = 'About'
  
  [[menus.main]]
    name = 'Who We Are'
    url = "/About/WhoWeAre"
    weight = 60 
    parent = 'About'
