baseURL = "https://symphonious-zuccutto-ade378.netlify.app/"
languageCode = "en-us"
title = ""
theme = "ananke"

 [menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'About'
    pageRef = '/About'
    weight = 2
  [[menus.main]]
    name = 'Forums'
    pageRef = '/Forums'
    weight = 3
  [[menus.main]]
    name = 'Guides'
    pageRef = '/Guides'
    weight = 4

    
     


